#!/usr/bin/perl
#
# $Id$
#

# system utilities paths
$MD5PATH="/sbin/md5";	# currently disabled
$PIDPATH="/var/run/named.pid";
$DIGPATH="/usr/bin/dig";
$SENDMAIL="/usr/sbin/sendmail";

# MD5 seed -- CHANGE THIS!
$MD5SEED="bf9bb421ef836495aa79ecd6ab6ca531";

# local URLs
$WHOISCGI="/adm/whois.cgi";

# hostname for whois
$WHOISHOST="whois.eu.org";

# local dns-manager location
$DNSDIR="/usr/local/dns-manager";

$DNSLIB="$DNSDIR/lib";		# libraries directory
$DNSBIN="$DNSDIR/bin";		# scripts directory
$DNSCONF="$DNSDIR/conf";	# configuration files directory
$ZONEDIR="$DNSDIR/zones";	# zone files directory
$VALDIR="$DNSDIR/val";		# spool directory for waiting requests
$REQDIR="$DNSDIR/spool";	# temp spool directory for e-mail forms

$DNSLOG="$DNSDIR/log";		# log file

# scripts
$AZPATH="$DNSBIN/access-zone";
$CHECKNSPATH="$DNSBIN/check-ns";
$CHECKCNAMEPATH="$DNSBIN/check-cname";
$CHECKMXPATH="$DNSBIN/check-mx";
$CRPATH="$DNSBIN/check-request";

$PASSFILE="$DNSCONF/user-info";		# user info file
$ZAUTFILE="$DNSCONF/zones-auth";	# zone authorizations file

# templates for mail requests
if ($ENV{'LANG'} eq 'en') {
	$DOMTEMP="$DNSCONF/domain-template.txt";
} else {
	$DOMTEMP="$DNSCONF/domain-template-$ENV{'LANG'}.txt";
}

# Enable real nameserver checking.
# Set this to 0 if you want to test while you're not connected.
$do_checkns=1;

# TO AVOID MAIL LOOPS, DON'T PUT dns-manager IN ANY ADDRESS !

# Address for the user to send acknowledges to
$MAILACK="dns-manager\@eu.org";
$MAILACKFR="dns-manager-fr\@eu.org";

# headers for replies to mail queries
$MAILHEADERS="From: hostmaster\@EU.org\nReply-To: %s\nBcc: pb\n";
#
# headers for validation/rejection mail to the requester
$VALHEADERS="From: hostmaster\@EU.org\nReply-To: %s\nBcc: pb\n";
#
# address to send whois database updates to
$WHOISDBM="auto-dbm@EU.org";
#
# name of database in generated objects ("source:" line)
$DBNAME="FREENIC";
