#!/usr/bin/perl
#
# $Id$
#

# Messages for the administrator validation CGI script

if ($ENV{'LANG'} eq 'fr') {

$MSG_SUBIN="Subject: requete [%s] (domaine %s)\n";
$MSG_BDYIN="Bonjour,\n\nVotre requête [%s] sur le domaine %s\nnécessite un complément d'informations :\n\n%s\n";
$MSG_SUBRJ="Subject: rejet de votre requete [%s] (domaine %s)\n";
$MSG_BDYRJ="Bonjour,\n\nMalheureusement, votre requête [%s] sur le domaine %s\na été rejetée pour la raison suivante :\n\n%s\n";
$MSG_SUBAC="Subject: requete [%s] (domaine %s) acceptee\n";
$MSG_BDYAC="Bonjour,\n\nVotre requête [%s] (domaine %s)\na été acceptée.\n\n";
$MSG_BDYZD="Les enregistrements suivants seront détruits du fichier de zone :\n\n";
$MSG_BDYZI="Les enregistrements suivants seront insérés dans le fichier de zone :\n\n";
$MSG_BDYWI="Les enregistrements suivants seront insérés dans la base WHOIS :\n\n";
$MSG_OKBYE="\nLeur propagation prendra environ une demi-journée.\n\tSalutations virtuelles,\n\tles gestionnaires de EU.org.\n\n";
$MSG_BYE="\n\n\tSalutations virtuelles,\n\tles gestionnaires de EU.org.\n\n";

} else {
$MSG_SUBIN="Subject: request [%s] (domain %s)\n";
$MSG_BDYIN="Hello,\n\nWe need additional information about your request [%s]\n(domain %s):\n\n%s\n";

$MSG_SUBRJ="Subject: request [%s] (domain %s) rejected\n";
$MSG_BDYRJ="Hello,\n\nSorry, your request [%s] (domain %s) has been rejected\nfor the following reason:\n\n%s\n";
$MSG_SUBAC="Subject: request [%s] (domain %s) accepted\n";
$MSG_BDYAC="Hello,\n\nYour request [%s] (domain %s) has been accepted.\n\n";
$MSG_BDYZD="The following records will be deleted from the zone file:\n\n";
$MSG_BDYZI="The following records will be inserted in the zone file:\n\n";
$MSG_BDYWI="The following records will be inserted in the WHOIS base:\n\n";
$MSG_OKBYE="\nPlease allow about half a day for propagation.\n\tVirtually yours,\n\tEU.org management.\n\n";
$MSG_BYE="\n\n\tVirtually yours,\n\tEU.org management.\n\n";

}
