#!/usr/bin/perl
#
# $Id$
#

# Messages for check-*

if ($ENV{'LANG'} eq 'fr') {
$ERR_BADD0="\nErreur: %s: domaine intermédiaire vide.\n";
$ERR_BADDB="\nErreur: %s: chaque partie doit commencer par une lettre\n";
$ERR_BADDE="\nErreur: %s: chaque partie doit se terminer par une lettre ou un chiffre\n";
$ERR_BADDM="\nErreur: %s: caractère(s) interdit(s) dans un nom de domaine.\n";
$ERR_BADEM="Erreur: \"%s\" n'est pas de la forme user\@host.domain.\n";
$ERR_BADNH="Erreur: \"%s\" ne ressemble pas à un NIC-Handle.\n";
$ERR_BADPH="Erreur: \"%s\": téléphone incorrect (doit débuter par +code-pays\n\tet ne contenir que des chiffres ou espaces).\n";
$ERR_BADRP="Erreur: l'adresse de réponse \"%s\" n'est pas de la forme user\@host.domain.\n";
$ERR_BADRR="Erreur: type d'enregistrement DNS \"%s\" non reconnu\n";
$ERR_BADRT="Erreur: type de requête \"%s\" non reconnu\n";
$ERR_INVCH="Erreur: \"%s\" contient des caractères invalides.\n";
$ERR_MISCT="Erreur: les contacts doivent être cités lors d'une création de domaine.\n";
$ERR_MISRC="Erreur: type d'enregistrement DNS manquant.\n";
$ERR_MISRQ="Erreur: type de requête manquant.\n";
$ERR_NOAEM="Erreur: pas d'adresse de courrier électronique pour le contact administratif.\n";
$ERR_NOANM="Erreur: pas de nom pour le contact administratif.\n";
$ERR_NOCTC="Erreur: aucun contact technique ni administratif.\n";
$ERR_NODOM="Erreur: pas de domaine spécifié.\n";
$ERR_NOEML="Erreur: pas d'adresse de courrier électronique pour le contact.\n";
$ERR_NONAM="Erreur: pas de nom pour le contact.\n";
$ERR_NOOAD="Erreur: pas d'adresse pour l'organisme.\n";
$ERR_NOORG="Erreur: aucun organisme.\n";
$ERR_NOPAR="Erreur: le domaine .%s n'est pas géré ici.\n";
$ERR_NOSRV="Erreur: aucun serveur spécifié.\n";
$ERR_NOTAM="Erreur: pas d'adresse de courrier électronique pour le contact technique.\n";
$ERR_NOTNM="Erreur: pas de nom pour le contact technique.\n";
$ERR_TWICE="Erreur: champ \"%s\" trouvé plus d'une fois.\n";
$ERR_UNKFT="Erreur: version de format inconnue.\n";
$ERR_UREPL="Erreur: \"%s\" n'est pas une des adresses de contact.\n";
$ERR_EMPTY="Erreur: requête vide.\n";

$MSG_BASCK="---- Vérifications de base\n\n";
$MSG_CNTCK="\n---- Vérification des contacts\n\n";
$MSG_ENDCK="\n---- Fin des vérifications\n\n";
$MSG_GENRC="\n---- Génération des enregistrements pour la zone %s\n\n";
$MSG_NBERR="%d erreur(s), arrêt.\n";
$MSG_NOADM="Pas de contact administratif, utilisation du contact technique.\n";
$MSG_NOTEC="Pas de contact technique, utilisation du contact administratif.\n";
$MSG_RQOK1="Votre requête est correcte, mais vous allez devoir la confirmer.\n";
$MSG_RQOK2="Pour cela, vous allez devoir répondre au courrier qui va\nvous être envoyé à l'adresse :\n\t%s\n\n";
$MSG_RQOKM="Vous devez envoyer un courrier électronique à %s,\navec un Subject: contenant :\n\t[%s]\nNormalement il vous suffit de répondre au présent message.\n";
$MSG_RQSUB="Subject: votre requete [%s]\n\n";
$MSG_TMPLT="Veuillez remplir et renvoyer le formulaire suivant :\n\n";
$MSG_WHOIS="\n---- Génération des informations WHOIS pour le domaine \"%s\"\n\n";

# for check-ns

$MSG_CSERV="\n---- Vérification des adresses de serveurs de noms\n\n";
$MSG_CNSRR="---- Vérification des enregistrements NS pour \"%s\" sur %s\n\n";
$MSG_ACCIP="Adresse IP %s acceptée pour %s (dans le domaine)\n";
$MSG_SERNO="Numéro de série %s sur %s (ayant autorité).\n";
$MSG_MAXSN="Numéro de série maximum trouvé %s ; %d serveur(s) pas à jour.\n";
$MSG_PRSOA="Le serveur primaire indiqué par le SOA est %s.\n";
$MSG_PRNNS="Attention: primaire %s absent de la liste de NS.\n";
$MSG_NSLOK="Liste de NS pour \"%s\" sur %s correcte.\n";
$MSG_OK="ok.\n";
$MSG_CHKNM="---- Vérification des serveurs et noms de domaine\n\n";
$MSG_CHKIP="Vérification adresse IP %s pour %s...";
$MSG_GETIP="Récupération de l'adresse IP pour %s...";
$MSG_NOREC="Impossible de montrer les enregistrements actuels.\n\n";
$MSG_NOINS="Impossible d'insérer les nouveaux enregistrements.\n\n";

$ERR_GHBNM="\nErreur: gethostbyname(%s): $s\n";
$ERR_NSMIS="Erreur: La liste de NS sur %s diffère de celle des serveurs parents'.\n";
$ERR_MISIP="Erreur: manque l'adresse IP pour %s (dans le domaine)\n";
$ERR_PROLD="Erreur: le numéro de série sur %s n'est pas le plus élevé !\n";
$ERR_HOSTU="\nErreur: machine inconnue.\n";
$ERR_CNAME="\nErreur: CNAME (vers %s).\n";
$ERR_NOARR="\nErreur: enregistrement A introuvable ou non concordant.\n";
$ERR_INVIP="\nErreur: %s: adresse IP invalide.\n";
$ERR_NSERR="Erreur: %s NS %s: erreur de serveur de nom (lame?):\n";
$ERR_NOAUT="Erreur: %s n'a pas autorité pour le domaine %s.\n";
$ERR_LAMEN="Erreur: mauvaise délégation (n'a pas autorité pour le domaine).\n";
$ERR_ERRNS="Erreur: impossible d'obtenir une réponse du serveur de noms %s.\n";

# for check-mx / check-cname

$ERR_ISCAN="Erreur: %s est un CNAME vers %s\n";
$ERR_DOMNA="Erreur: %s n'a pas d'enregistrement A.\n";
$ERR_NOTF="Erreur: %s n'existe pas.\n";

} else {

$ERR_BADD0="\nError: %s: empty domain part.\n";
$ERR_BADDB="\nError: %s: domain part must begin with a letter\n";
$ERR_BADDE="\nError: %s: domain part must end with a letter or digit\n";
$ERR_BADDM="\nError: %s: invalid character(s) in domain name.\n";
$ERR_BADEM="Error: \"%s\" is not a valid RFC822 (user\@host.domain) address.\n";
$ERR_BADNH="Error: \"%s\" does not look like a valid NIC handle.\n";
$ERR_BADPH="Error: \"%s\" invalid phone (should start with +country-code\n\tand contain only digits or spaces).\n";
$ERR_BADRP="Error: reply address \"%s\" is not a valid RFC822 (user\@host.domain) address.\n";
$ERR_BADRR="Error: unrecognized resource record type \"%s\"\n";
$ERR_BADRT="Error: unrecognized request type \"%s\"\n";
$ERR_INVCH="Error: \"%s\" contains invalid characters.\n";
$ERR_MISCT="Error: contact information is mandatory for a domain creation.\n";
$ERR_MISRC="Error: resource record type missing.\n";
$ERR_MISRQ="Error: request type missing.\n";
$ERR_NOAEM="Error: no e-mail for admin contact.\n";
$ERR_NOANM="Error: no name for admin contact.\n";
$ERR_NOCTC="Error: no technical nor administrative contact given.\n";
$ERR_NODOM="Error: No domain specified.\n";
$ERR_NOEML="Error: no e-mail for contact.\n";
$ERR_NONAM="Error: no name for contact.\n";
$ERR_NOOAD="Error: no organization address.\n";
$ERR_NOORG="Error: no organization.\n";
$ERR_NOPAR="Error: domain .%s is not managed here.\n";
$ERR_NOSRV="Error: no server specified.\n";
$ERR_NOTAM="Error: no e-mail for tech contact.\n";
$ERR_NOTNM="Error: no name for tech contact.\n";
$ERR_TWICE="Error: id \"%s\" found twice.\n";
$ERR_UNKFT="Error: unknown format version.\n";
$ERR_UREPL="Error: reply address \"%s\" is not one of the contact addresses.\n";
$ERR_EMPTY="Error: empty request.\n";

$MSG_BASCK="---- Basic checks\n\n";
$MSG_CNTCK="\n---- Contacts checks\n\n";
$MSG_ENDCK="\n---- End of checks\n\n";
$MSG_GENRC="\n---- Generating records for %s zonefile\n\n";
$MSG_NBERR="%d error(s), stopping.\n";
$MSG_NOADM="No administrative contact given, using technical contact.\n";
$MSG_NOTEC="No technical contact given, using administrative contact.\n";
$MSG_RQOK1="Your request is correct, but you will be requested an e-mail acknowledge.\n\n";
$MSG_RQOK2="You will have to reply to the message sent to:\n\t%s\n\n";
$MSG_RQOKM="You just need to send an e-mail to %s, with a Subject: containing:\n\t[%s]\nSimply replying to this current message should be enough.\n";
$MSG_RQSUB="Subject: your request [%s]\n\n";
$MSG_TMPLT="Please fill-in and resend the following template:\n\n";
$MSG_WHOIS="\n---- Generating WHOIS info for domain \"%s\"\n\n";

# for check-ns

$MSG_CSERV="\n---- Checking server addresses\n\n";
$MSG_CNSRR="---- Checking NS records for \"%s\" on %s\n\n";
$MSG_ACCIP="Accepting IP %s for %s (in domain)\n";
$MSG_SERNO="Found serial number %s on %s (authoritative).\n";
$MSG_MAXSN="Maximum serial number is %s; %d server(s) not up to date.\n";
$MSG_PRSOA="Primary indicated by SOA is %s.\n";
$MSG_PRNNS="Warning: primary %s not in NS list.\n";
$MSG_NSLOK="NS list for \"%s\" on %s is correct.\n";
$MSG_OK="ok.\n";
$MSG_CHKNM="---- Servers and domain names check\n\n";
$MSG_CHKIP="Checking IP %s for %s...";
$MSG_GETIP="Getting IP for %s...";
$MSG_NOREC="Unable to show existing records.\n\n";
$MSG_NOINS="Unable to insert records.\n\n";

$ERR_GHBNM="\nError: gethostbyname(%s): $s\n";
$ERR_NSMIS="Error: NS list on %s does not match parent servers'.\n";
$ERR_MISIP="Error: missing IP for %s (in domain)\n";
$ERR_PROLD="Error: serial number on %s is not the highest !\n";
$ERR_HOSTU="\nError: unknown host.\n";
$ERR_CNAME="\nError: CNAME (to %s).\n";
$ERR_NOARR="\nError: A record not found or mismatch.\n";
$ERR_INVIP="\nError: %s: invalid IP address.\n";
$ERR_NSERR="Error: %s NS %s: nameserver error (lame?):\n";
$ERR_NOAUT="Error: %s not authoritative for domain %s.\n";
$ERR_LAMEN="Error: Lame NS delegation (not authoritative for domain).\n";
$ERR_ERRNS="Error: no answer from nameserver on %s.\n";

# for check-mx / check-cname

$ERR_ISCAN="Error: %s is a CNAME to %s\n";
$ERR_DOMNA="Error: %s has no A record.\n";
$ERR_NOTF="Error: %s does not exist.\n";
}
