#!/usr/bin/perl
#
# $Id$
#

# Messages and addresses for e-mails

if ($ENV{'LANG'} eq 'fr') {

$MSG_ADDR=$MAILACKFR;
$MSG_SUBIN="Subject: requete [%s] (domaine %s)\n";
$MSG_BDYIN="Bonjour,\n\nVotre requête [%s] sur le domaine %s\nnécessite un complément d'informations :\n\n%s\n";
$MSG_SUBRJ="Subject: rejet de votre requete [%s] (domaine %s)\n";
$MSG_BDYRJ="Bonjour,\n\nMalheureusement, votre requête [%s] sur le domaine %s\na été rejetée pour la raison suivante :\n\n%s\n";
$MSG_SUBAC="Subject: requete [%s] (domaine %s) acceptee\n";
$MSG_BDYAC="Bonjour,\n\nVotre requête [%s] (domaine %s)\na été acceptée.\n\n";
$MSG_BDYZD="Les enregistrements suivants seront détruits du fichier de zone :\n\n";
$MSG_BDYZI="Les enregistrements suivants seront insérés dans le fichier de zone :\n\n";
$MSG_BDYWI="Les enregistrements suivants seront insérés dans la base WHOIS :\n\n";
$MSG_RQOK0="Bonjour,\n\nNous avons reçu de vous la requête suivante.\n\n";
$MSG_RQOK1="Cette requête est correcte, mais vous devez la confirmer.\n";
$MSG_RQOK2="Pour cela, il vous suffira de répondre au courrier qui va vous être\nenvoyé à l'adresse :\n\t%s\n\n";
$MSG_RQOKM="Vous devez envoyer un courrier électronique à %s,\navec un Subject: contenant :\n\n\t[%s]\n\nNormalement il vous suffit de répondre au présent message.\n";
$MSG_RQOKR="Copie de votre requête :\n\n";
$MSG_RQOKW="Enregistrements whois :\n\n";
$MSG_RQOKD="Enregistrements DNS :\n\n";
$MSG_RQM="Modification du domaine %s\n";
$MSG_RQN="Nouveau domaine %s\n";
$MSG_RQD="Destruction du domaine %s\n";
$MSG_ACKOK="Bonjour,\n\nVotre confirmation de la requête [%s] est acceptée.\n\nVous serez notifié dès le traitement de la requête.\n";
$MSG_ACKKO="Votre confirmation de la requête [%s] ne correspond pas\nà une requête en attente, et n'a donc pas été prise en compte.\n";
$MSG_OKBYE="\nLeur propagation prendra environ une demi-journée.\n\tSalutations virtuelles,\n\tles gestionnaires de EU.org.\n\n";
$MSG_OKRMB="\nLa zone étant tenue à jour manuellement, votre requête est transmise\nau responsable.\n\tSalutations virtuelles,\n\tles gestionnaires de EU.org.\n\n";
$MSG_BYE="\n\n\tSalutations virtuelles,\n\tles gestionnaires de EU.org.\n\n";

} else {

$MSG_ADDR=$MAILACK;
$MSG_SUBIN="Subject: request [%s] (domain %s)\n";
$MSG_BDYIN="Hello,\n\nWe need additional information about your request [%s]\n(domain %s):\n\n%s\n";

$MSG_SUBRJ="Subject: request [%s] (domain %s) rejected\n";
$MSG_BDYRJ="Hello,\n\nSorry, your request [%s] (domain %s) has been rejected\nfor the following reason:\n\n%s\n";
$MSG_SUBAC="Subject: request [%s] (domain %s) accepted\n";
$MSG_BDYAC="Hello,\n\nYour request [%s] (domain %s)\nhas been accepted.\n\n";
$MSG_BDYZD="The following records will be deleted from the zone file:\n\n";
$MSG_BDYZI="The following records will be inserted in the zone file:\n\n";
$MSG_BDYWI="The following records will be inserted in the WHOIS base:\n\n";
$MSG_RQOK0="Hello,\n\nWe have received the following request from you.\n\n";
$MSG_RQOK1="The request is correct, but you need to acknowledge it.\n\n";
$MSG_RQOK2="An acknowledge request is being sent to:\n\t%s\n\nYou will just have to send a reply when you receive it.\n";
$MSG_RQOKM="You just need to send an e-mail to %s,\nwith a Subject: containing:\n\n\t[%s]\n\nSimply replying to this current message should be enough.\n";
$MSG_RQOKR="Copy of your request:\n\n";
$MSG_RQOKW="Whois records:\n\n";
$MSG_RQOKD="DNS records:\n\n";
$MSG_RQM="Modification of domain %s\n";
$MSG_RQN="New domain %s\n";
$MSG_RQD="Deletion of domain %s\n";
$MSG_ACKOK="Hello,\n\nYour acknowledgement for request [%s] is accepted.\n\nYou will receive a notification when your request has been processed.\n";
$MSG_ACKKO="Hello,\n\nYour acknowledgement for request [%s] does not match\nany pending request. It has been ignored, sorry.\n";
$MSG_OKBYE="\nPlease allow about half a day for propagation.\n\tVirtually yours,\n\tEU.org management.\n\n";
$MSG_OKRMB="\nAs the zone is handled by hand, your request is being forwarded to\nthe maintainer.\n\tVirtually yours,\n\tEU.org management.\n\n";
$MSG_BYE="\n\n\tVirtually yours,\n\tEU.org management.\n\n";

}
