#!/usr/bin/perl
#
# $Id$
#
#
# CGI script to handle a POSTed form and pipe it to $CRPATH
#

# local configuration.
require "/usr/local/autoreg/conf/config";
require "$DNSLIB/cgi.pl";

print "HTTP/1.0 200 OK\n";
print "Content-type: text/html\n";
print "Server: $ENV{'SERVER_SOFTWARE'}\n\n";

print "<HTML><HEAD>";
print "<TITLE>DNS query result</TITLE>\n";
print "</HEAD><BODY>\n";
print "<H1>DNS query result</H1>\n";
print "<PRE>\n";

&content;

select(STDOUT); $| = 1; print ""; $| = 0;

system("date >> $DNSLOG");

if (!open(CHECKREQ, "|$CRPATH w3 2>&1 | tee -a $DNSLOG")) {
  print "Can't start $CRPATH: $!\n";
  return;
}

print CHECKREQ "REMOTE_USER: $ENV{'REMOTE_USER'}\n";
print CHECKREQ "REMOTE_HOST: $ENV{'REMOTE_HOST'}\n";
print CHECKREQ "\nDomain Version Number: E1.0\n\n";

foreach $key (keys %content) {
  print CHECKREQ "$key.: $content{$key}\n";
}

close(CHECKREQ);

print "</PRE></BODY></HTML>\n";
