#!/usr/bin/perl
#
# $Id$
#

# local configuration.
$whois="/usr/bin/whois";
require "/usr/local/dns-manager/lib/cgi.pl";

sub doform {
   print <<EOF;
<FORM ACTION="$ENV{'SCRIPT_NAME'}" METHOD="GET">
Server: <INPUT NAME="server" VALUE="$content{'server'}"><P>
Request: <INPUT NAME="request" VALUE="$content{'request'}"><P>
<INPUT TYPE="submit" VALUE="Submit">
</FORM>
EOF

}

sub dowhois {
   print "<HR>\n";
   $content{'server'} =~ s/["';&]//g;
   $content{'request'} =~ s/["';&]//g;

   if (!open(WHOIS, "whois -h \"$content{'server'}\" \"$content{'request'}\"|")) {
      print "<STRONG>Can't execute whois: $!</STRONG>\n";
      return;
   }
   print "<TT>whois -h $content{'server'} $content{'request'}</TT>\n";
   print "<HR><PRE>\n";
   while (<WHOIS>) {
      s/</&lt;/g;
      s/>/&gt;/g;
      print;
   }
   print "</PRE><HR>\n";
   close(WHOIS);
}

print "Content-Type: text/html\n\n<HTML><HEAD>";
print "</HEAD><BODY>\n";

&content;
&doform;

if ($content{'request'}) { &dowhois; }

print "</BODY></HTML>\n";
