#!/usr/bin/perl
#
# $Id$
#

require "/usr/local/dns-manager/lib/cgi.pl";
require "/usr/local/dns-manager/lib/whois.pl";

sub doform {
   print <<EOF;
<FORM ACTION="$ENV{'SCRIPT_NAME'}" METHOD="GET">
Server: <INPUT NAME="server" VALUE="$content{'server'}"><P>
Request: <INPUT NAME="request" VALUE="$content{'request'}"><P>
<INPUT TYPE="submit" VALUE="Submit">
</FORM>
EOF

}

print "Content-Type: text/html\n\n<HTML><HEAD>";
print "</HEAD><BODY>\n";

&content;
&doform;

if ($content{'request'}) {
  print "<HR>\n";
  &whois_html($content{'server'}, $content{'request'});
}

print "</BODY></HTML>\n";
