#!/bin/sh
Z=$1
SRV1=$2
SRV2=$3

#
# canonicalize zone
#
zonefilter()
{
  python -c "
import re
import sys
re_line = re.compile('^(\S+)\s+(\d+)\s+IN\s+(\S+)\s+(.*)$')

for line in sys.stdin:
  line = line[:-1]
  m = re_line.match(line)
  if m:
    mg = m.groups()
    if mg[2] in ['DS', 'TLSA']:
      v1, v2, v3, hash = mg[3].split(None, 3)
      if len(hash) > 56 and hash[56] == ' ':
        hash = hash[:56] + hash[57:]
      mg = mg[0], mg[1], mg[2], ' '.join([v1, v2, v3, hash.lower()])
    print('%s\t%s\t%s\t%s' % mg)
  else:
    print(line)
" |
  awk '
	/^; Transfer failed./ { exit 1 }
	/^\s*$/ { next }
	/^;/ { next }
	$3 == "SOA" { if (!soaseen) { print "serial " $6 >"/dev/stderr"; } soaseen += 1; next }
	$3 != "RRSIG" && $3 != "NSEC" && $3 != "NSEC3" && $3 != "TYPE65534" && $3 != "TYPE65535" { print }
	END { if (soaseen != 2) { print "FAIL" >"/dev/stderr"; exit 1 } }
  ' | sort
}

zoneaxfr()
{
  Z=$1
  SRV=$2
  echo "Transfering ${Z} from ${SRV}... " > /dev/stderr
  dig @${SRV} axfr ${Z}
}

zonedb()
{
  Z=$1
  SRV=$2
  echo "Transfering ${Z} from database... " > /dev/stderr
  access-zone -R -acat ${Z}
}

FILE1=/tmp/ZD-${Z}-${SRV1}.tmp
FILE2=/tmp/ZD-${Z}-${SRV2}.tmp

if [ ${SRV1} == "db" ]; then
  zonedb ${Z} | zonefilter > ${FILE1}
else
  zoneaxfr ${Z} ${SRV1} | zonefilter > ${FILE1}
fi

if [ ${SRV2} == "db" ]; then
  zonedb ${Z} | zonefilter > ${FILE2}
else
  zoneaxfr ${Z} ${SRV2} | zonefilter > ${FILE2}
fi

# Convert the diff output to add/del statements, nsupdate-style.
diff -u ${FILE1} ${FILE2} | tail +3 | awk '/^\+/ { print "add " substr($0, 2) } /^-/ { print "del " substr($0, 2) }'
rm -f ${FILE1} ${FILE2}
